"""Replace resume_file_url with resume_file_path

Revision ID: 43658ca1f6e6
Revises: d6635294a8a0
Create Date: 2025-10-29 18:07:27.493660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43658ca1f6e6'
down_revision: Union[str, Sequence[str], None] = 'd6635294a8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_file_path', sa.String(), nullable=True))
    op.drop_column('candidates', 'resume_file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resume_file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('candidates', 'resume_file_path')
    # ### end Alembic commands ###
