"""add candidate parsed fields

Revision ID: d6635294a8a0
Revises: 80f29f0887b6
Create Date: 2025-10-04 03:23:12.958618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6635294a8a0'
down_revision: Union[str, Sequence[str], None] = '80f29f0887b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('education_details', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('experiences', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('raw_text', sa.Text(), nullable=True))
    op.drop_column('candidates', 'education')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'raw_text')
    op.drop_column('candidates', 'experiences')
    op.drop_column('candidates', 'education_details')
    # ### end Alembic commands ###
